<?php
session_start();
$timeout_duration = 7200;

if (!isset($_SESSION['username'])) {
    header("Location: index.php");
    exit();
}
if (isset($_SESSION['LAST_ACTIVITY']) && (time() - $_SESSION['LAST_ACTIVITY']) > $timeout_duration) {
    session_unset();
    session_destroy();
    header("Location: index.php?expired=true");
    exit();
}
$_SESSION['LAST_ACTIVITY'] = time();
$userName = $_SESSION['username'];

include "db.php";
require_once('tcpdf/tcpdf.php');

// --- Get filters from GET parameters ---
$organization = isset($_GET['organization']) ? trim($_GET['organization']) : "";
$userFilter   = isset($_GET['user']) ? trim($_GET['user']) : "";
$startDate    = isset($_GET['startDate']) ? trim($_GET['startDate']) : "";
$endDate      = isset($_GET['endDate']) ? trim($_GET['endDate']) : "";

// --- Build SQL query with filters ---
$where = "WHERE status='ongoing'";

if ($organization !== "") $where .= " AND organization LIKE '%" . $conn->real_escape_string($organization) . "%'";
if ($userFilter !== "") $where .= " AND assignedBy LIKE '%" . $conn->real_escape_string($userFilter) . "%'";
if ($startDate !== "" && $endDate !== "") {
    $start = $conn->real_escape_string($startDate);
    $end   = $conn->real_escape_string($endDate);
    $where .= " AND assignedDate BETWEEN '$start' AND '$end'";
}

$sql = "SELECT organization, location, tenderNo, bidSecurity, assignedBy, closingDate, assignedDate
        FROM tenders
        $where
        ORDER BY closingDate DESC";

$result = $conn->query($sql);

// --- Initialize TCPDF ---
$pdf = new TCPDF('L', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('Powernet Tenders');
$pdf->SetAuthor($userName);
$pdf->SetTitle('Ongoing Tenders Report');
$pdf->SetMargins(10, 10, 10);
$pdf->SetAutoPageBreak(TRUE, 10);
$pdf->AddPage();

// --- PDF Header ---
$html = '<h2 style="text-align:center;">Ongoing Tenders Report</h2>';
$html .= '<p><strong>Generated by:</strong> ' . htmlspecialchars($userName) . '</p>';

if($startDate !== "" && $endDate !== ""){
    $html .= "<p><strong>Period:</strong> $startDate to $endDate</p>";
}

$html .= '<table border="1" cellpadding="4" cellspacing="0">
            <thead style="background-color:#f2f2f2;">
                <tr>
                    <th><b>Organization</b></th>
                    <th><b>Location</b></th>
                    <th><b>Tender No</b></th>
                    <th><b>Bid Security</b></th>
                    <th><b>Assigned Person</b></th>
                    <th><b>Closing Date</b></th>
                </tr>
            </thead>
            <tbody>';

if ($result && $result->num_rows > 0) {
    while($row = $result->fetch_assoc()){
        $html .= '<tr>
                    <td>'.htmlspecialchars($row['organization']).'</td>
                    <td>'.htmlspecialchars($row['location']).'</td>
                    <td>'.htmlspecialchars($row['tenderNo']).'</td>
                    <td>'.htmlspecialchars($row['bidSecurity']).'</td>
                    <td>'.htmlspecialchars($row['assignedBy']).'</td>
                    <td>'.htmlspecialchars($row['closingDate']).'</td>
                  </tr>';
    }
} else {
    $html .= '<tr><td colspan="6" style="text-align:center;">No data found for selected filters</td></tr>';
}

$html .= '</tbody></table>';

// --- Output PDF ---
$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output('Ongoing_Tenders_Report.pdf', 'I');
